backend:
  name: git-gateway
  branch: main

media_folder: "imagenes"
public_folder: "/imagenes"

collections:
  - name: "noticias"
    label: "Noticias"
    folder: "sections/noticias"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    filter: { field: "title", value: "index", negate: true }
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Imagen", name: "image", widget: "image" }
      - { label: "Resumen", name: "excerpt", widget: "text" }
      - { label: "Contenido", name: "body", widget: "markdown" }
      - { label: "Plantilla", name: "layout", widget: "hidden", default: "noticia.njk" }
